### ISSUE TITLE
Upload spec source = File not working for Command Line Runner

### ISSUE THREAD

**Issue by santhonisz** [jfrog/teamcity-artifactory-plugin#33] opened 2017-08-28 07:14 UTC
When using the Command Line Runner in TeamCity, setting the Artifactory _Upload spec source_ field to "File" and entering the path to a file containing the upload spec in the _Spec path_ field seems to have no effect - there are no files uploaded, no errors and nothing in the build log? 
Setting the _Upload spec source_ field to "Job Configuration" and entering the spec directly continues to work fine.

**Comment by cschyma** [comment] 2018-07-03 14:22
Anything new on this?

This is still happening with Plugin version 2.6.0 and Artifactory 5.8.3.

**Comment by torsten-liermann** [comment] 2018-07-08 12:10
I also do not know why JFrog takes so much time with it. The implementation also does not make a professional impression.

**Comment by eyalbe4** [comment] 2018-07-08 13:13
@torsten-liermann and @cschyma,
This issue should have been investigated sooner. My apologies for this :(
We're investigating this now and will update soon.

**Comment by eyalbe4** [comment] 2018-07-09 15:38
@torsten-liermann and @cschyma,
We opened [TCAP-317](https://www.jfrog.com/jira/browse/TCAP-317) which includes the root cause for the issue you reported here.
We also pushed [this](https://github.com/jfrog/teamcity-artifactory-plugin/commit/09276b0e3825b91635048ebea134a0ac01607378) commit which fixes the issue by prompting a clear error message to the build log.
We created a snapshot version of the Artifactory Plugin with the fix. You can download it using this link:
https://oss.jfrog.org/artifactory/oss-snapshot-local/org/jfrog/teamcity/teamcity-artifactory-plugin-assembly/2.6.x-SNAPSHOT/teamcity-artifactory-plugin-assembly-2.6.x-20180709.151423-2.zip
We'd appreciate your feedback for the fix.

**Comment by eyalbe4** [comment] 2018-08-20 08:11
@torsten-liermann and @cschyma,
I'm closing this issue for now. Version 2.7.0 is about to be released and it includes this fix.
We'd appreciate any feedback you can provide for the fix.

**Closed by eyalbe4** 2018-08-20 08:11 UTC
